project:
  type: website
  output-dir: docs

website:
  title: "descSPIM_LSmicro"
  favicon: ""
  open-graph: true
  search: true
  navbar:
    background: light
    logo: ""
    logo-alt: ""
    logo-href: ""
    collapse-below: lg
    
    left:
      - href: index.qmd
        text: "Home"
      - href: about.qmd
        text: "About"
      - href: Software.qmd
        text: "Software"
  
      - text: "Protocols"
        menu: 
          - href: supplementary/Protocols/Cubic/cubic.qmd
            text: "Cubic"
          - href: supplementary/Protocols/gel/gel.qmd
            text: "Gel embeding"

      - text: "Supplementary"
        menu: 
          - href: supplementary/3dimaging/index.qmd
            text: "3D Imaging"
          - href: supplementary/construction/index.qmd
            text: "Construction"
          - href: supplementary/OpticalAligment/OpticalAligment.qmd
            text: "Optical Aligment"
            
      - href: blog.qmd
        text: "Reports"

    right: 
      - icon: github
        href: "https://marcelorosales.github.io/descSPIM_LSmicro/"
      - icon: rss

  sidebar:
    - id: cubic 
      title: "Cubic Protocols"
      style: "floating"
      collapse-level: 3
      align: left
      contents:  
        - text: "Intro"
          href: supplementary/Protocols/Cubic/cubic.qmd  
        - text: "Cubic"
          href: supplementary/Protocols/Cubic/cubic02.qmd  
        - text: "Cubic HV"
          href: supplementary/Protocols/Cubic/cubic_hv.qmd   
        - text: ""
          href: ""

    - id: gel
      title: "Cubic Protocols"
      style: "floating"
      collapse-level: 3
      align: left
      contents:  
        - text: "Gel Embedding"
          href: supplementary/Protocols/gel/gel.qmd
        - text: ""
          href: ""  
        - text: ""
          href: ""

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    code-link: true
    toc: true
    include-after-body: js.html
    self-contained: false
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

editor: source

