project:
  type: website
  output-dir: docs

website:
  title: "descSPIM_LSmicro"
  favicon: ""
  open-graph: true
  search: true
  navbar:
    background: light
    logo: ""
    logo-alt: ""
    logo-href: ""
    collapse-below: lg
    
    left:
      - text: "Home"
        href: index.qmd
      - about.qmd
      - text: "Software"
        href: Software.qmd
        
      - text: "Protocols"
        menu: 
          - text: "Cubic"
            href: supplementary/Protocols/Cubic/Cubic.qmd
  
      - text: "Supplementary"
        menu: 
          - text: "3D Imaging"
            href: supplementary/3dimaging/index.qmd
          - text: "Construction"
            href: supplementary/construction/index.qmd
          - text: "Optical Aligment"
            href: supplementary/OpticalAligment/OpticalAligment.qmd

    right: 
      - icon: github
        href: "https://marcelorosales.github.io/descSPIM_LSmicro/"
      - icon: rss

  sidebar: 
    - id: ""

format:
  html:
    theme: 
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    css: styles.css
    code-copy: true
    code-overflow: wrap
    code-link: true
    toc: true
    include-after-body: js.html
    self-contained: false
    grid:
      sidebar-width: 250px
      body-width: 900px
      margin-width: 300px

editor: source

