name: 🚀 FTP Deploy

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.4
        with:
          server: ftp.descsimp.online # Subdomain name?
          username: ${{ secrets.FTP_USERNAME }} # Set in github
          password: ${{ secrets.FTP_PASSWORD }} # Set in github
          local-dir: ./docs
          remote-dir: /public_html/lsmicro # or subdomain folder